// <auto-generated>
/*
 * Hydrus Client API
 *
 * API for interacting with the Hydrus Client
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using HydrusAPI.NET.Client;

namespace HydrusAPI.NET.Model
{
    /// <summary>
    /// AddFilesGenerateHashesRequest
    /// </summary>
    public partial class AddFilesGenerateHashesRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddFilesGenerateHashesRequest" /> class.
        /// </summary>
        /// <param name="path">The file system path of the file to import and generate hashes for.</param>
        [JsonConstructor]
        public AddFilesGenerateHashesRequest(Option<string?> path = default)
        {
            PathOption = path;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Path
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PathOption { get; private set; }

        /// <summary>
        /// The file system path of the file to import and generate hashes for.
        /// </summary>
        /// <value>The file system path of the file to import and generate hashes for.</value>
        [JsonPropertyName("path")]
        public string? Path { get { return this.PathOption; } set { this.PathOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddFilesGenerateHashesRequest {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AddFilesGenerateHashesRequest" />
    /// </summary>
    public class AddFilesGenerateHashesRequestJsonConverter : JsonConverter<AddFilesGenerateHashesRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="AddFilesGenerateHashesRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AddFilesGenerateHashesRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> path = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "path":
                            path = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (path.IsSet && path.Value == null)
                throw new ArgumentNullException(nameof(path), "Property is not nullable for class AddFilesGenerateHashesRequest.");

            return new AddFilesGenerateHashesRequest(path);
        }

        /// <summary>
        /// Serializes a <see cref="AddFilesGenerateHashesRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addFilesGenerateHashesRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AddFilesGenerateHashesRequest addFilesGenerateHashesRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, addFilesGenerateHashesRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AddFilesGenerateHashesRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addFilesGenerateHashesRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AddFilesGenerateHashesRequest addFilesGenerateHashesRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (addFilesGenerateHashesRequest.PathOption.IsSet && addFilesGenerateHashesRequest.Path == null)
                throw new ArgumentNullException(nameof(addFilesGenerateHashesRequest.Path), "Property is required for class AddFilesGenerateHashesRequest.");

            if (addFilesGenerateHashesRequest.PathOption.IsSet)
                writer.WriteString("path", addFilesGenerateHashesRequest.Path);
        }
    }

    /// <summary>
    /// The AddFilesGenerateHashesRequestSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(AddFilesGenerateHashesRequest))]
    public partial class AddFilesGenerateHashesRequestSerializationContext : JsonSerializerContext { }
}
