// <auto-generated>
/*
 * Hydrus Client API
 *
 * API for interacting with the Hydrus Client
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using HydrusAPI.NET.Client;

namespace HydrusAPI.NET.Model
{
    /// <summary>
    /// AddTagsSearchTags200ResponseTagsInner
    /// </summary>
    public partial class AddTagsSearchTags200ResponseTagsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddTagsSearchTags200ResponseTagsInner" /> class.
        /// </summary>
        /// <param name="value">value</param>
        /// <param name="count">count</param>
        [JsonConstructor]
        public AddTagsSearchTags200ResponseTagsInner(string value, int? count = default)
        {
            Value = value;
            Count = count;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [JsonPropertyName("count")]
        public int? Count { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddTagsSearchTags200ResponseTagsInner {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AddTagsSearchTags200ResponseTagsInner" />
    /// </summary>
    public class AddTagsSearchTags200ResponseTagsInnerJsonConverter : JsonConverter<AddTagsSearchTags200ResponseTagsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="AddTagsSearchTags200ResponseTagsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AddTagsSearchTags200ResponseTagsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> value = default;
            Option<int?> count = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "count":
                            count = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!value.IsSet)
                throw new ArgumentException("Property is required for class AddTagsSearchTags200ResponseTagsInner.", nameof(value));

            if (!count.IsSet)
                throw new ArgumentException("Property is required for class AddTagsSearchTags200ResponseTagsInner.", nameof(count));

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class AddTagsSearchTags200ResponseTagsInner.");

            return new AddTagsSearchTags200ResponseTagsInner(value.Value!, count.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AddTagsSearchTags200ResponseTagsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addTagsSearchTags200ResponseTagsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AddTagsSearchTags200ResponseTagsInner addTagsSearchTags200ResponseTagsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, addTagsSearchTags200ResponseTagsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AddTagsSearchTags200ResponseTagsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addTagsSearchTags200ResponseTagsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AddTagsSearchTags200ResponseTagsInner addTagsSearchTags200ResponseTagsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (addTagsSearchTags200ResponseTagsInner.Value == null)
                throw new ArgumentNullException(nameof(addTagsSearchTags200ResponseTagsInner.Value), "Property is required for class AddTagsSearchTags200ResponseTagsInner.");

            writer.WriteString("value", addTagsSearchTags200ResponseTagsInner.Value);

            if (addTagsSearchTags200ResponseTagsInner.Count != null)
                writer.WriteNumber("count", addTagsSearchTags200ResponseTagsInner.Count.Value);
            else
                writer.WriteNull("count");
        }
    }

    /// <summary>
    /// The AddTagsSearchTags200ResponseTagsInnerSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(AddTagsSearchTags200ResponseTagsInner))]
    public partial class AddTagsSearchTags200ResponseTagsInnerSerializationContext : JsonSerializerContext { }
}
