// <auto-generated>
/*
 * Hydrus Client API
 *
 * API for interacting with the Hydrus Client
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using HydrusAPI.NET.Client;

namespace HydrusAPI.NET.Model
{
    /// <summary>
    /// AddUrlsGetUrlFiles200Response
    /// </summary>
    public partial class AddUrlsGetUrlFiles200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddUrlsGetUrlFiles200Response" /> class.
        /// </summary>
        /// <param name="normalisedUrl">normalisedUrl</param>
        /// <param name="urlFileStatuses">urlFileStatuses</param>
        [JsonConstructor]
        public AddUrlsGetUrlFiles200Response(Option<string?> normalisedUrl = default, Option<List<AddUrlsGetUrlFiles200ResponseUrlFileStatusesInner>?> urlFileStatuses = default)
        {
            NormalisedUrlOption = normalisedUrl;
            UrlFileStatusesOption = urlFileStatuses;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of NormalisedUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NormalisedUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets NormalisedUrl
        /// </summary>
        [JsonPropertyName("normalised_url")]
        public string? NormalisedUrl { get { return this.NormalisedUrlOption; } set { this.NormalisedUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of UrlFileStatuses
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<AddUrlsGetUrlFiles200ResponseUrlFileStatusesInner>?> UrlFileStatusesOption { get; private set; }

        /// <summary>
        /// Gets or Sets UrlFileStatuses
        /// </summary>
        [JsonPropertyName("url_file_statuses")]
        public List<AddUrlsGetUrlFiles200ResponseUrlFileStatusesInner>? UrlFileStatuses { get { return this.UrlFileStatusesOption; } set { this.UrlFileStatusesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddUrlsGetUrlFiles200Response {\n");
            sb.Append("  NormalisedUrl: ").Append(NormalisedUrl).Append("\n");
            sb.Append("  UrlFileStatuses: ").Append(UrlFileStatuses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AddUrlsGetUrlFiles200Response" />
    /// </summary>
    public class AddUrlsGetUrlFiles200ResponseJsonConverter : JsonConverter<AddUrlsGetUrlFiles200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="AddUrlsGetUrlFiles200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AddUrlsGetUrlFiles200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> normalisedUrl = default;
            Option<List<AddUrlsGetUrlFiles200ResponseUrlFileStatusesInner>?> urlFileStatuses = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "normalised_url":
                            normalisedUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "url_file_statuses":
                            urlFileStatuses = new Option<List<AddUrlsGetUrlFiles200ResponseUrlFileStatusesInner>?>(JsonSerializer.Deserialize<List<AddUrlsGetUrlFiles200ResponseUrlFileStatusesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (normalisedUrl.IsSet && normalisedUrl.Value == null)
                throw new ArgumentNullException(nameof(normalisedUrl), "Property is not nullable for class AddUrlsGetUrlFiles200Response.");

            if (urlFileStatuses.IsSet && urlFileStatuses.Value == null)
                throw new ArgumentNullException(nameof(urlFileStatuses), "Property is not nullable for class AddUrlsGetUrlFiles200Response.");

            return new AddUrlsGetUrlFiles200Response(normalisedUrl, urlFileStatuses);
        }

        /// <summary>
        /// Serializes a <see cref="AddUrlsGetUrlFiles200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addUrlsGetUrlFiles200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AddUrlsGetUrlFiles200Response addUrlsGetUrlFiles200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, addUrlsGetUrlFiles200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AddUrlsGetUrlFiles200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addUrlsGetUrlFiles200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AddUrlsGetUrlFiles200Response addUrlsGetUrlFiles200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (addUrlsGetUrlFiles200Response.NormalisedUrlOption.IsSet && addUrlsGetUrlFiles200Response.NormalisedUrl == null)
                throw new ArgumentNullException(nameof(addUrlsGetUrlFiles200Response.NormalisedUrl), "Property is required for class AddUrlsGetUrlFiles200Response.");

            if (addUrlsGetUrlFiles200Response.UrlFileStatusesOption.IsSet && addUrlsGetUrlFiles200Response.UrlFileStatuses == null)
                throw new ArgumentNullException(nameof(addUrlsGetUrlFiles200Response.UrlFileStatuses), "Property is required for class AddUrlsGetUrlFiles200Response.");

            if (addUrlsGetUrlFiles200Response.NormalisedUrlOption.IsSet)
                writer.WriteString("normalised_url", addUrlsGetUrlFiles200Response.NormalisedUrl);

            if (addUrlsGetUrlFiles200Response.UrlFileStatusesOption.IsSet)
            {
                writer.WritePropertyName("url_file_statuses");
                JsonSerializer.Serialize(writer, addUrlsGetUrlFiles200Response.UrlFileStatuses, jsonSerializerOptions);
            }
        }
    }

    /// <summary>
    /// The AddUrlsGetUrlFiles200ResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(AddUrlsGetUrlFiles200Response))]
    public partial class AddUrlsGetUrlFiles200ResponseSerializationContext : JsonSerializerContext { }
}
