// <auto-generated>
/*
 * Hydrus Client API
 *
 * API for interacting with the Hydrus Client
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using HydrusAPI.NET.Client;

namespace HydrusAPI.NET.Model
{
    /// <summary>
    /// GetFilesSearchFiles200Response
    /// </summary>
    public partial class GetFilesSearchFiles200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetFilesSearchFiles200Response" /> class.
        /// </summary>
        /// <param name="fileIds">A list of numerical file IDs.</param>
        /// <param name="hashes">A list of SHA256 hashes.</param>
        [JsonConstructor]
        public GetFilesSearchFiles200Response(Option<List<int>?> fileIds = default, Option<List<string>?> hashes = default)
        {
            FileIdsOption = fileIds;
            HashesOption = hashes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of FileIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<int>?> FileIdsOption { get; private set; }

        /// <summary>
        /// A list of numerical file IDs.
        /// </summary>
        /// <value>A list of numerical file IDs.</value>
        /* <example>[125462, 4852415, 123]</example> */
        [JsonPropertyName("file_ids")]
        public List<int>? FileIds { get { return this.FileIdsOption; } set { this.FileIdsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Hashes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> HashesOption { get; private set; }

        /// <summary>
        /// A list of SHA256 hashes.
        /// </summary>
        /// <value>A list of SHA256 hashes.</value>
        /* <example>[1b04c4df7accd5a61c5d02b36658295686b0abfebdc863110e7d7249bba3f9ad, fe416723c731d679aa4d20e9fd36727f4a38cd0ac6d035431f0f452fad54563f]</example> */
        [JsonPropertyName("hashes")]
        public List<string>? Hashes { get { return this.HashesOption; } set { this.HashesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetFilesSearchFiles200Response {\n");
            sb.Append("  FileIds: ").Append(FileIds).Append("\n");
            sb.Append("  Hashes: ").Append(Hashes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetFilesSearchFiles200Response" />
    /// </summary>
    public class GetFilesSearchFiles200ResponseJsonConverter : JsonConverter<GetFilesSearchFiles200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetFilesSearchFiles200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetFilesSearchFiles200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<int>?> fileIds = default;
            Option<List<string>?> hashes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "file_ids":
                            fileIds = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "hashes":
                            hashes = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (fileIds.IsSet && fileIds.Value == null)
                throw new ArgumentNullException(nameof(fileIds), "Property is not nullable for class GetFilesSearchFiles200Response.");

            if (hashes.IsSet && hashes.Value == null)
                throw new ArgumentNullException(nameof(hashes), "Property is not nullable for class GetFilesSearchFiles200Response.");

            return new GetFilesSearchFiles200Response(fileIds, hashes);
        }

        /// <summary>
        /// Serializes a <see cref="GetFilesSearchFiles200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getFilesSearchFiles200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetFilesSearchFiles200Response getFilesSearchFiles200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getFilesSearchFiles200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetFilesSearchFiles200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getFilesSearchFiles200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetFilesSearchFiles200Response getFilesSearchFiles200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getFilesSearchFiles200Response.FileIdsOption.IsSet && getFilesSearchFiles200Response.FileIds == null)
                throw new ArgumentNullException(nameof(getFilesSearchFiles200Response.FileIds), "Property is required for class GetFilesSearchFiles200Response.");

            if (getFilesSearchFiles200Response.HashesOption.IsSet && getFilesSearchFiles200Response.Hashes == null)
                throw new ArgumentNullException(nameof(getFilesSearchFiles200Response.Hashes), "Property is required for class GetFilesSearchFiles200Response.");

            if (getFilesSearchFiles200Response.FileIdsOption.IsSet)
            {
                writer.WritePropertyName("file_ids");
                JsonSerializer.Serialize(writer, getFilesSearchFiles200Response.FileIds, jsonSerializerOptions);
            }
            if (getFilesSearchFiles200Response.HashesOption.IsSet)
            {
                writer.WritePropertyName("hashes");
                JsonSerializer.Serialize(writer, getFilesSearchFiles200Response.Hashes, jsonSerializerOptions);
            }
        }
    }

    /// <summary>
    /// The GetFilesSearchFiles200ResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(GetFilesSearchFiles200Response))]
    public partial class GetFilesSearchFiles200ResponseSerializationContext : JsonSerializerContext { }
}
