// <auto-generated>
/*
 * Hydrus Client API
 *
 * API for interacting with the Hydrus Client
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using HydrusAPI.NET.Client;

namespace HydrusAPI.NET.Model
{
    /// <summary>
    /// GetService200ResponseService
    /// </summary>
    public partial class GetService200ResponseService : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetService200ResponseService" /> class.
        /// </summary>
        /// <param name="name">The human-readable name of the service.</param>
        /// <param name="serviceKey">The unique hex identifier of the service.</param>
        /// <param name="type">The service type as an integer enum.</param>
        /// <param name="typePretty">A human-readable description of the service type.</param>
        [JsonConstructor]
        public GetService200ResponseService(Option<string?> name = default, Option<string?> serviceKey = default, Option<int?> type = default, Option<string?> typePretty = default)
        {
            NameOption = name;
            ServiceKeyOption = serviceKey;
            TypeOption = type;
            TypePrettyOption = typePretty;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// The human-readable name of the service.
        /// </summary>
        /// <value>The human-readable name of the service.</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ServiceKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ServiceKeyOption { get; private set; }

        /// <summary>
        /// The unique hex identifier of the service.
        /// </summary>
        /// <value>The unique hex identifier of the service.</value>
        [JsonPropertyName("service_key")]
        public string? ServiceKey { get { return this.ServiceKeyOption; } set { this.ServiceKeyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TypeOption { get; private set; }

        /// <summary>
        /// The service type as an integer enum.
        /// </summary>
        /// <value>The service type as an integer enum.</value>
        [JsonPropertyName("type")]
        public int? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of TypePretty
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TypePrettyOption { get; private set; }

        /// <summary>
        /// A human-readable description of the service type.
        /// </summary>
        /// <value>A human-readable description of the service type.</value>
        [JsonPropertyName("type_pretty")]
        public string? TypePretty { get { return this.TypePrettyOption; } set { this.TypePrettyOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetService200ResponseService {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ServiceKey: ").Append(ServiceKey).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  TypePretty: ").Append(TypePretty).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetService200ResponseService" />
    /// </summary>
    public class GetService200ResponseServiceJsonConverter : JsonConverter<GetService200ResponseService>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetService200ResponseService" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetService200ResponseService Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> serviceKey = default;
            Option<int?> type = default;
            Option<string?> typePretty = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "service_key":
                            serviceKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            type = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "type_pretty":
                            typePretty = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class GetService200ResponseService.");

            if (serviceKey.IsSet && serviceKey.Value == null)
                throw new ArgumentNullException(nameof(serviceKey), "Property is not nullable for class GetService200ResponseService.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class GetService200ResponseService.");

            if (typePretty.IsSet && typePretty.Value == null)
                throw new ArgumentNullException(nameof(typePretty), "Property is not nullable for class GetService200ResponseService.");

            return new GetService200ResponseService(name, serviceKey, type, typePretty);
        }

        /// <summary>
        /// Serializes a <see cref="GetService200ResponseService" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getService200ResponseService"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetService200ResponseService getService200ResponseService, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getService200ResponseService, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetService200ResponseService" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getService200ResponseService"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetService200ResponseService getService200ResponseService, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getService200ResponseService.NameOption.IsSet && getService200ResponseService.Name == null)
                throw new ArgumentNullException(nameof(getService200ResponseService.Name), "Property is required for class GetService200ResponseService.");

            if (getService200ResponseService.ServiceKeyOption.IsSet && getService200ResponseService.ServiceKey == null)
                throw new ArgumentNullException(nameof(getService200ResponseService.ServiceKey), "Property is required for class GetService200ResponseService.");

            if (getService200ResponseService.TypePrettyOption.IsSet && getService200ResponseService.TypePretty == null)
                throw new ArgumentNullException(nameof(getService200ResponseService.TypePretty), "Property is required for class GetService200ResponseService.");

            if (getService200ResponseService.NameOption.IsSet)
                writer.WriteString("name", getService200ResponseService.Name);

            if (getService200ResponseService.ServiceKeyOption.IsSet)
                writer.WriteString("service_key", getService200ResponseService.ServiceKey);

            if (getService200ResponseService.TypeOption.IsSet)
                writer.WriteNumber("type", getService200ResponseService.TypeOption.Value!.Value);

            if (getService200ResponseService.TypePrettyOption.IsSet)
                writer.WriteString("type_pretty", getService200ResponseService.TypePretty);
        }
    }

    /// <summary>
    /// The GetService200ResponseServiceSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(GetService200ResponseService))]
    public partial class GetService200ResponseServiceSerializationContext : JsonSerializerContext { }
}
