// <auto-generated>
/*
 * Hydrus Client API
 *
 * API for interacting with the Hydrus Client
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using HydrusAPI.NET.Client;

namespace HydrusAPI.NET.Model
{
    /// <summary>
    /// ManageCookiesGetCookies200Response
    /// </summary>
    public partial class ManageCookiesGetCookies200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ManageCookiesGetCookies200Response" /> class.
        /// </summary>
        /// <param name="cookies">cookies</param>
        [JsonConstructor]
        public ManageCookiesGetCookies200Response(Option<List<List<string>>?> cookies = default)
        {
            CookiesOption = cookies;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Cookies
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<List<string>>?> CookiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Cookies
        /// </summary>
        [JsonPropertyName("cookies")]
        public List<List<string>>? Cookies { get { return this.CookiesOption; } set { this.CookiesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ManageCookiesGetCookies200Response {\n");
            sb.Append("  Cookies: ").Append(Cookies).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ManageCookiesGetCookies200Response" />
    /// </summary>
    public class ManageCookiesGetCookies200ResponseJsonConverter : JsonConverter<ManageCookiesGetCookies200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="ManageCookiesGetCookies200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ManageCookiesGetCookies200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<List<string>>?> cookies = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "cookies":
                            cookies = new Option<List<List<string>>?>(JsonSerializer.Deserialize<List<List<string>>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (cookies.IsSet && cookies.Value == null)
                throw new ArgumentNullException(nameof(cookies), "Property is not nullable for class ManageCookiesGetCookies200Response.");

            return new ManageCookiesGetCookies200Response(cookies);
        }

        /// <summary>
        /// Serializes a <see cref="ManageCookiesGetCookies200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manageCookiesGetCookies200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ManageCookiesGetCookies200Response manageCookiesGetCookies200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, manageCookiesGetCookies200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ManageCookiesGetCookies200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manageCookiesGetCookies200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ManageCookiesGetCookies200Response manageCookiesGetCookies200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (manageCookiesGetCookies200Response.CookiesOption.IsSet && manageCookiesGetCookies200Response.Cookies == null)
                throw new ArgumentNullException(nameof(manageCookiesGetCookies200Response.Cookies), "Property is required for class ManageCookiesGetCookies200Response.");

            if (manageCookiesGetCookies200Response.CookiesOption.IsSet)
            {
                writer.WritePropertyName("cookies");
                JsonSerializer.Serialize(writer, manageCookiesGetCookies200Response.Cookies, jsonSerializerOptions);
            }
        }
    }

    /// <summary>
    /// The ManageCookiesGetCookies200ResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ManageCookiesGetCookies200Response))]
    public partial class ManageCookiesGetCookies200ResponseSerializationContext : JsonSerializerContext { }
}
