// <auto-generated>
/*
 * Hydrus Client API
 *
 * API for interacting with the Hydrus Client
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using HydrusAPI.NET.Client;

namespace HydrusAPI.NET.Model
{
    /// <summary>
    /// ManageServicesForgetPendingRequest
    /// </summary>
    public partial class ManageServicesForgetPendingRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ManageServicesForgetPendingRequest" /> class.
        /// </summary>
        /// <param name="serviceKey">The hexadecimal service key for which to forget pending content.</param>
        [JsonConstructor]
        public ManageServicesForgetPendingRequest(string serviceKey)
        {
            ServiceKey = serviceKey;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The hexadecimal service key for which to forget pending content.
        /// </summary>
        /// <value>The hexadecimal service key for which to forget pending content.</value>
        [JsonPropertyName("service_key")]
        public string ServiceKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ManageServicesForgetPendingRequest {\n");
            sb.Append("  ServiceKey: ").Append(ServiceKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ManageServicesForgetPendingRequest" />
    /// </summary>
    public class ManageServicesForgetPendingRequestJsonConverter : JsonConverter<ManageServicesForgetPendingRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ManageServicesForgetPendingRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ManageServicesForgetPendingRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> serviceKey = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "service_key":
                            serviceKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!serviceKey.IsSet)
                throw new ArgumentException("Property is required for class ManageServicesForgetPendingRequest.", nameof(serviceKey));

            if (serviceKey.IsSet && serviceKey.Value == null)
                throw new ArgumentNullException(nameof(serviceKey), "Property is not nullable for class ManageServicesForgetPendingRequest.");

            return new ManageServicesForgetPendingRequest(serviceKey.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ManageServicesForgetPendingRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manageServicesForgetPendingRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ManageServicesForgetPendingRequest manageServicesForgetPendingRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, manageServicesForgetPendingRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ManageServicesForgetPendingRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manageServicesForgetPendingRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ManageServicesForgetPendingRequest manageServicesForgetPendingRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (manageServicesForgetPendingRequest.ServiceKey == null)
                throw new ArgumentNullException(nameof(manageServicesForgetPendingRequest.ServiceKey), "Property is required for class ManageServicesForgetPendingRequest.");

            writer.WriteString("service_key", manageServicesForgetPendingRequest.ServiceKey);
        }
    }

    /// <summary>
    /// The ManageServicesForgetPendingRequestSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ManageServicesForgetPendingRequest))]
    public partial class ManageServicesForgetPendingRequestSerializationContext : JsonSerializerContext { }
}
