// <auto-generated>
/*
 * Hydrus Client API
 *
 * API for interacting with the Hydrus Client
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using HydrusAPI.NET.Client;

namespace HydrusAPI.NET.Model
{
    /// <summary>
    /// ManageHeadersGetHeaders200Response
    /// </summary>
    public partial class ManageHeadersGetHeaders200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ManageHeadersGetHeaders200Response" /> class.
        /// </summary>
        /// <param name="networkContext">networkContext</param>
        /// <param name="headers">headers</param>
        [JsonConstructor]
        public ManageHeadersGetHeaders200Response(ManageHeadersGetHeaders200ResponseNetworkContext networkContext, Dictionary<string, ManageHeadersGetHeaders200ResponseHeadersValue> headers)
        {
            NetworkContext = networkContext;
            Headers = headers;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets NetworkContext
        /// </summary>
        [JsonPropertyName("network_context")]
        public ManageHeadersGetHeaders200ResponseNetworkContext NetworkContext { get; set; }

        /// <summary>
        /// Gets or Sets Headers
        /// </summary>
        [JsonPropertyName("headers")]
        public Dictionary<string, ManageHeadersGetHeaders200ResponseHeadersValue> Headers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ManageHeadersGetHeaders200Response {\n");
            sb.Append("  NetworkContext: ").Append(NetworkContext).Append("\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ManageHeadersGetHeaders200Response" />
    /// </summary>
    public class ManageHeadersGetHeaders200ResponseJsonConverter : JsonConverter<ManageHeadersGetHeaders200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="ManageHeadersGetHeaders200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ManageHeadersGetHeaders200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ManageHeadersGetHeaders200ResponseNetworkContext?> networkContext = default;
            Option<Dictionary<string, ManageHeadersGetHeaders200ResponseHeadersValue>?> headers = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "network_context":
                            networkContext = new Option<ManageHeadersGetHeaders200ResponseNetworkContext?>(JsonSerializer.Deserialize<ManageHeadersGetHeaders200ResponseNetworkContext>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "headers":
                            headers = new Option<Dictionary<string, ManageHeadersGetHeaders200ResponseHeadersValue>?>(JsonSerializer.Deserialize<Dictionary<string, ManageHeadersGetHeaders200ResponseHeadersValue>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!networkContext.IsSet)
                throw new ArgumentException("Property is required for class ManageHeadersGetHeaders200Response.", nameof(networkContext));

            if (!headers.IsSet)
                throw new ArgumentException("Property is required for class ManageHeadersGetHeaders200Response.", nameof(headers));

            if (networkContext.IsSet && networkContext.Value == null)
                throw new ArgumentNullException(nameof(networkContext), "Property is not nullable for class ManageHeadersGetHeaders200Response.");

            if (headers.IsSet && headers.Value == null)
                throw new ArgumentNullException(nameof(headers), "Property is not nullable for class ManageHeadersGetHeaders200Response.");

            return new ManageHeadersGetHeaders200Response(networkContext.Value!, headers.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ManageHeadersGetHeaders200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manageHeadersGetHeaders200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ManageHeadersGetHeaders200Response manageHeadersGetHeaders200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, manageHeadersGetHeaders200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ManageHeadersGetHeaders200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manageHeadersGetHeaders200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ManageHeadersGetHeaders200Response manageHeadersGetHeaders200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (manageHeadersGetHeaders200Response.NetworkContext == null)
                throw new ArgumentNullException(nameof(manageHeadersGetHeaders200Response.NetworkContext), "Property is required for class ManageHeadersGetHeaders200Response.");

            if (manageHeadersGetHeaders200Response.Headers == null)
                throw new ArgumentNullException(nameof(manageHeadersGetHeaders200Response.Headers), "Property is required for class ManageHeadersGetHeaders200Response.");

            writer.WritePropertyName("network_context");
            JsonSerializer.Serialize(writer, manageHeadersGetHeaders200Response.NetworkContext, jsonSerializerOptions);
            writer.WritePropertyName("headers");
            JsonSerializer.Serialize(writer, manageHeadersGetHeaders200Response.Headers, jsonSerializerOptions);
        }
    }

    /// <summary>
    /// The ManageHeadersGetHeaders200ResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ManageHeadersGetHeaders200Response))]
    public partial class ManageHeadersGetHeaders200ResponseSerializationContext : JsonSerializerContext { }
}
