// <auto-generated>
/*
 * Hydrus Client API
 *
 * API for interacting with the Hydrus Client
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using HydrusAPI.NET.Client;

namespace HydrusAPI.NET.Model
{
    /// <summary>
    /// NetworkJobMetadata
    /// </summary>
    public partial class NetworkJobMetadata : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkJobMetadata" /> class.
        /// </summary>
        /// <param name="url">url</param>
        /// <param name="waitingOnConnectionError">waitingOnConnectionError</param>
        /// <param name="domainOk">domainOk</param>
        /// <param name="waitingOnServersideBandwidth">waitingOnServersideBandwidth</param>
        /// <param name="noEngineYet">noEngineYet</param>
        /// <param name="hasError">hasError</param>
        /// <param name="totalDataUsed">totalDataUsed</param>
        /// <param name="isDone">isDone</param>
        /// <param name="statusText">statusText</param>
        /// <param name="currentSpeed">currentSpeed</param>
        /// <param name="bytesRead">bytesRead</param>
        /// <param name="bytesToRead">bytesToRead</param>
        [JsonConstructor]
        public NetworkJobMetadata(Option<string?> url = default, Option<bool?> waitingOnConnectionError = default, Option<bool?> domainOk = default, Option<bool?> waitingOnServersideBandwidth = default, Option<bool?> noEngineYet = default, Option<bool?> hasError = default, Option<int?> totalDataUsed = default, Option<bool?> isDone = default, Option<string?> statusText = default, Option<int?> currentSpeed = default, Option<int?> bytesRead = default, Option<int?> bytesToRead = default)
        {
            UrlOption = url;
            WaitingOnConnectionErrorOption = waitingOnConnectionError;
            DomainOkOption = domainOk;
            WaitingOnServersideBandwidthOption = waitingOnServersideBandwidth;
            NoEngineYetOption = noEngineYet;
            HasErrorOption = hasError;
            TotalDataUsedOption = totalDataUsed;
            IsDoneOption = isDone;
            StatusTextOption = statusText;
            CurrentSpeedOption = currentSpeed;
            BytesReadOption = bytesRead;
            BytesToReadOption = bytesToRead;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string? Url { get { return this.UrlOption; } set { this.UrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of WaitingOnConnectionError
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> WaitingOnConnectionErrorOption { get; private set; }

        /// <summary>
        /// Gets or Sets WaitingOnConnectionError
        /// </summary>
        [JsonPropertyName("waiting_on_connection_error")]
        public bool? WaitingOnConnectionError { get { return this.WaitingOnConnectionErrorOption; } set { this.WaitingOnConnectionErrorOption = new(value); } }

        /// <summary>
        /// Used to track the state of DomainOk
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DomainOkOption { get; private set; }

        /// <summary>
        /// Gets or Sets DomainOk
        /// </summary>
        [JsonPropertyName("domain_ok")]
        public bool? DomainOk { get { return this.DomainOkOption; } set { this.DomainOkOption = new(value); } }

        /// <summary>
        /// Used to track the state of WaitingOnServersideBandwidth
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> WaitingOnServersideBandwidthOption { get; private set; }

        /// <summary>
        /// Gets or Sets WaitingOnServersideBandwidth
        /// </summary>
        [JsonPropertyName("waiting_on_serverside_bandwidth")]
        public bool? WaitingOnServersideBandwidth { get { return this.WaitingOnServersideBandwidthOption; } set { this.WaitingOnServersideBandwidthOption = new(value); } }

        /// <summary>
        /// Used to track the state of NoEngineYet
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> NoEngineYetOption { get; private set; }

        /// <summary>
        /// Gets or Sets NoEngineYet
        /// </summary>
        [JsonPropertyName("no_engine_yet")]
        public bool? NoEngineYet { get { return this.NoEngineYetOption; } set { this.NoEngineYetOption = new(value); } }

        /// <summary>
        /// Used to track the state of HasError
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HasErrorOption { get; private set; }

        /// <summary>
        /// Gets or Sets HasError
        /// </summary>
        [JsonPropertyName("has_error")]
        public bool? HasError { get { return this.HasErrorOption; } set { this.HasErrorOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalDataUsed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalDataUsedOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalDataUsed
        /// </summary>
        [JsonPropertyName("total_data_used")]
        public int? TotalDataUsed { get { return this.TotalDataUsedOption; } set { this.TotalDataUsedOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsDone
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsDoneOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsDone
        /// </summary>
        [JsonPropertyName("is_done")]
        public bool? IsDone { get { return this.IsDoneOption; } set { this.IsDoneOption = new(value); } }

        /// <summary>
        /// Used to track the state of StatusText
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusTextOption { get; private set; }

        /// <summary>
        /// Gets or Sets StatusText
        /// </summary>
        [JsonPropertyName("status_text")]
        public string? StatusText { get { return this.StatusTextOption; } set { this.StatusTextOption = new(value); } }

        /// <summary>
        /// Used to track the state of CurrentSpeed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CurrentSpeedOption { get; private set; }

        /// <summary>
        /// Gets or Sets CurrentSpeed
        /// </summary>
        [JsonPropertyName("current_speed")]
        public int? CurrentSpeed { get { return this.CurrentSpeedOption; } set { this.CurrentSpeedOption = new(value); } }

        /// <summary>
        /// Used to track the state of BytesRead
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BytesReadOption { get; private set; }

        /// <summary>
        /// Gets or Sets BytesRead
        /// </summary>
        [JsonPropertyName("bytes_read")]
        public int? BytesRead { get { return this.BytesReadOption; } set { this.BytesReadOption = new(value); } }

        /// <summary>
        /// Used to track the state of BytesToRead
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BytesToReadOption { get; private set; }

        /// <summary>
        /// Gets or Sets BytesToRead
        /// </summary>
        [JsonPropertyName("bytes_to_read")]
        public int? BytesToRead { get { return this.BytesToReadOption; } set { this.BytesToReadOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NetworkJobMetadata {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  WaitingOnConnectionError: ").Append(WaitingOnConnectionError).Append("\n");
            sb.Append("  DomainOk: ").Append(DomainOk).Append("\n");
            sb.Append("  WaitingOnServersideBandwidth: ").Append(WaitingOnServersideBandwidth).Append("\n");
            sb.Append("  NoEngineYet: ").Append(NoEngineYet).Append("\n");
            sb.Append("  HasError: ").Append(HasError).Append("\n");
            sb.Append("  TotalDataUsed: ").Append(TotalDataUsed).Append("\n");
            sb.Append("  IsDone: ").Append(IsDone).Append("\n");
            sb.Append("  StatusText: ").Append(StatusText).Append("\n");
            sb.Append("  CurrentSpeed: ").Append(CurrentSpeed).Append("\n");
            sb.Append("  BytesRead: ").Append(BytesRead).Append("\n");
            sb.Append("  BytesToRead: ").Append(BytesToRead).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NetworkJobMetadata" />
    /// </summary>
    public class NetworkJobMetadataJsonConverter : JsonConverter<NetworkJobMetadata>
    {
        /// <summary>
        /// Deserializes json to <see cref="NetworkJobMetadata" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NetworkJobMetadata Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> url = default;
            Option<bool?> waitingOnConnectionError = default;
            Option<bool?> domainOk = default;
            Option<bool?> waitingOnServersideBandwidth = default;
            Option<bool?> noEngineYet = default;
            Option<bool?> hasError = default;
            Option<int?> totalDataUsed = default;
            Option<bool?> isDone = default;
            Option<string?> statusText = default;
            Option<int?> currentSpeed = default;
            Option<int?> bytesRead = default;
            Option<int?> bytesToRead = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "waiting_on_connection_error":
                            waitingOnConnectionError = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "domain_ok":
                            domainOk = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "waiting_on_serverside_bandwidth":
                            waitingOnServersideBandwidth = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "no_engine_yet":
                            noEngineYet = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "has_error":
                            hasError = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "total_data_used":
                            totalDataUsed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "is_done":
                            isDone = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "status_text":
                            statusText = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "current_speed":
                            currentSpeed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "bytes_read":
                            bytesRead = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "bytes_to_read":
                            bytesToRead = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class NetworkJobMetadata.");

            if (waitingOnConnectionError.IsSet && waitingOnConnectionError.Value == null)
                throw new ArgumentNullException(nameof(waitingOnConnectionError), "Property is not nullable for class NetworkJobMetadata.");

            if (domainOk.IsSet && domainOk.Value == null)
                throw new ArgumentNullException(nameof(domainOk), "Property is not nullable for class NetworkJobMetadata.");

            if (waitingOnServersideBandwidth.IsSet && waitingOnServersideBandwidth.Value == null)
                throw new ArgumentNullException(nameof(waitingOnServersideBandwidth), "Property is not nullable for class NetworkJobMetadata.");

            if (noEngineYet.IsSet && noEngineYet.Value == null)
                throw new ArgumentNullException(nameof(noEngineYet), "Property is not nullable for class NetworkJobMetadata.");

            if (hasError.IsSet && hasError.Value == null)
                throw new ArgumentNullException(nameof(hasError), "Property is not nullable for class NetworkJobMetadata.");

            if (isDone.IsSet && isDone.Value == null)
                throw new ArgumentNullException(nameof(isDone), "Property is not nullable for class NetworkJobMetadata.");

            if (statusText.IsSet && statusText.Value == null)
                throw new ArgumentNullException(nameof(statusText), "Property is not nullable for class NetworkJobMetadata.");

            return new NetworkJobMetadata(url, waitingOnConnectionError, domainOk, waitingOnServersideBandwidth, noEngineYet, hasError, totalDataUsed, isDone, statusText, currentSpeed, bytesRead, bytesToRead);
        }

        /// <summary>
        /// Serializes a <see cref="NetworkJobMetadata" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="networkJobMetadata"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NetworkJobMetadata networkJobMetadata, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, networkJobMetadata, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NetworkJobMetadata" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="networkJobMetadata"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NetworkJobMetadata networkJobMetadata, JsonSerializerOptions jsonSerializerOptions)
        {
            if (networkJobMetadata.UrlOption.IsSet && networkJobMetadata.Url == null)
                throw new ArgumentNullException(nameof(networkJobMetadata.Url), "Property is required for class NetworkJobMetadata.");

            if (networkJobMetadata.StatusTextOption.IsSet && networkJobMetadata.StatusText == null)
                throw new ArgumentNullException(nameof(networkJobMetadata.StatusText), "Property is required for class NetworkJobMetadata.");

            if (networkJobMetadata.UrlOption.IsSet)
                writer.WriteString("url", networkJobMetadata.Url);

            if (networkJobMetadata.WaitingOnConnectionErrorOption.IsSet)
                writer.WriteBoolean("waiting_on_connection_error", networkJobMetadata.WaitingOnConnectionErrorOption.Value!.Value);

            if (networkJobMetadata.DomainOkOption.IsSet)
                writer.WriteBoolean("domain_ok", networkJobMetadata.DomainOkOption.Value!.Value);

            if (networkJobMetadata.WaitingOnServersideBandwidthOption.IsSet)
                writer.WriteBoolean("waiting_on_serverside_bandwidth", networkJobMetadata.WaitingOnServersideBandwidthOption.Value!.Value);

            if (networkJobMetadata.NoEngineYetOption.IsSet)
                writer.WriteBoolean("no_engine_yet", networkJobMetadata.NoEngineYetOption.Value!.Value);

            if (networkJobMetadata.HasErrorOption.IsSet)
                writer.WriteBoolean("has_error", networkJobMetadata.HasErrorOption.Value!.Value);

            if (networkJobMetadata.TotalDataUsedOption.IsSet)
                if (networkJobMetadata.TotalDataUsedOption.Value != null)
                    writer.WriteNumber("total_data_used", networkJobMetadata.TotalDataUsedOption.Value!.Value);
                else
                    writer.WriteNull("total_data_used");

            if (networkJobMetadata.IsDoneOption.IsSet)
                writer.WriteBoolean("is_done", networkJobMetadata.IsDoneOption.Value!.Value);

            if (networkJobMetadata.StatusTextOption.IsSet)
                writer.WriteString("status_text", networkJobMetadata.StatusText);

            if (networkJobMetadata.CurrentSpeedOption.IsSet)
                if (networkJobMetadata.CurrentSpeedOption.Value != null)
                    writer.WriteNumber("current_speed", networkJobMetadata.CurrentSpeedOption.Value!.Value);
                else
                    writer.WriteNull("current_speed");

            if (networkJobMetadata.BytesReadOption.IsSet)
                if (networkJobMetadata.BytesReadOption.Value != null)
                    writer.WriteNumber("bytes_read", networkJobMetadata.BytesReadOption.Value!.Value);
                else
                    writer.WriteNull("bytes_read");

            if (networkJobMetadata.BytesToReadOption.IsSet)
                if (networkJobMetadata.BytesToReadOption.Value != null)
                    writer.WriteNumber("bytes_to_read", networkJobMetadata.BytesToReadOption.Value!.Value);
                else
                    writer.WriteNull("bytes_to_read");
        }
    }

    /// <summary>
    /// The NetworkJobMetadataSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(NetworkJobMetadata))]
    public partial class NetworkJobMetadataSerializationContext : JsonSerializerContext { }
}
