// <auto-generated>
/*
 * Hydrus Client API
 *
 * API for interacting with the Hydrus Client
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using HydrusAPI.NET.Client;

namespace HydrusAPI.NET.Model
{
    /// <summary>
    /// PageInfoResponsePageInfoManagement
    /// </summary>
    public partial class PageInfoResponsePageInfoManagement : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PageInfoResponsePageInfoManagement" /> class.
        /// </summary>
        /// <param name="multipleWatcherImport">multipleWatcherImport</param>
        [JsonConstructor]
        public PageInfoResponsePageInfoManagement(Option<PageInfoResponsePageInfoManagementMultipleWatcherImport?> multipleWatcherImport = default)
        {
            MultipleWatcherImportOption = multipleWatcherImport;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of MultipleWatcherImport
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PageInfoResponsePageInfoManagementMultipleWatcherImport?> MultipleWatcherImportOption { get; private set; }

        /// <summary>
        /// Gets or Sets MultipleWatcherImport
        /// </summary>
        [JsonPropertyName("multiple_watcher_import")]
        public PageInfoResponsePageInfoManagementMultipleWatcherImport? MultipleWatcherImport { get { return this.MultipleWatcherImportOption; } set { this.MultipleWatcherImportOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PageInfoResponsePageInfoManagement {\n");
            sb.Append("  MultipleWatcherImport: ").Append(MultipleWatcherImport).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PageInfoResponsePageInfoManagement" />
    /// </summary>
    public class PageInfoResponsePageInfoManagementJsonConverter : JsonConverter<PageInfoResponsePageInfoManagement>
    {
        /// <summary>
        /// Deserializes json to <see cref="PageInfoResponsePageInfoManagement" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PageInfoResponsePageInfoManagement Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PageInfoResponsePageInfoManagementMultipleWatcherImport?> multipleWatcherImport = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "multiple_watcher_import":
                            multipleWatcherImport = new Option<PageInfoResponsePageInfoManagementMultipleWatcherImport?>(JsonSerializer.Deserialize<PageInfoResponsePageInfoManagementMultipleWatcherImport>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (multipleWatcherImport.IsSet && multipleWatcherImport.Value == null)
                throw new ArgumentNullException(nameof(multipleWatcherImport), "Property is not nullable for class PageInfoResponsePageInfoManagement.");

            return new PageInfoResponsePageInfoManagement(multipleWatcherImport);
        }

        /// <summary>
        /// Serializes a <see cref="PageInfoResponsePageInfoManagement" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pageInfoResponsePageInfoManagement"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PageInfoResponsePageInfoManagement pageInfoResponsePageInfoManagement, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, pageInfoResponsePageInfoManagement, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PageInfoResponsePageInfoManagement" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pageInfoResponsePageInfoManagement"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PageInfoResponsePageInfoManagement pageInfoResponsePageInfoManagement, JsonSerializerOptions jsonSerializerOptions)
        {
            if (pageInfoResponsePageInfoManagement.MultipleWatcherImportOption.IsSet && pageInfoResponsePageInfoManagement.MultipleWatcherImport == null)
                throw new ArgumentNullException(nameof(pageInfoResponsePageInfoManagement.MultipleWatcherImport), "Property is required for class PageInfoResponsePageInfoManagement.");

            if (pageInfoResponsePageInfoManagement.MultipleWatcherImportOption.IsSet)
            {
                writer.WritePropertyName("multiple_watcher_import");
                JsonSerializer.Serialize(writer, pageInfoResponsePageInfoManagement.MultipleWatcherImport, jsonSerializerOptions);
            }
        }
    }

    /// <summary>
    /// The PageInfoResponsePageInfoManagementSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(PageInfoResponsePageInfoManagement))]
    public partial class PageInfoResponsePageInfoManagementSerializationContext : JsonSerializerContext { }
}
