// <auto-generated>
/*
 * Hydrus Client API
 *
 * API for interacting with the Hydrus Client
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using HydrusAPI.NET.Client;

namespace HydrusAPI.NET.Model
{
    /// <summary>
    /// SessionKey200Response
    /// </summary>
    public partial class SessionKey200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SessionKey200Response" /> class.
        /// </summary>
        /// <param name="sessionKey">Hexadecimal string representing the session key</param>
        [JsonConstructor]
        public SessionKey200Response(string sessionKey)
        {
            SessionKey = sessionKey;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Hexadecimal string representing the session key
        /// </summary>
        /// <value>Hexadecimal string representing the session key</value>
        [JsonPropertyName("session_key")]
        public string SessionKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SessionKey200Response {\n");
            sb.Append("  SessionKey: ").Append(SessionKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SessionKey200Response" />
    /// </summary>
    public class SessionKey200ResponseJsonConverter : JsonConverter<SessionKey200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="SessionKey200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SessionKey200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> sessionKey = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "session_key":
                            sessionKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!sessionKey.IsSet)
                throw new ArgumentException("Property is required for class SessionKey200Response.", nameof(sessionKey));

            if (sessionKey.IsSet && sessionKey.Value == null)
                throw new ArgumentNullException(nameof(sessionKey), "Property is not nullable for class SessionKey200Response.");

            return new SessionKey200Response(sessionKey.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SessionKey200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sessionKey200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SessionKey200Response sessionKey200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sessionKey200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SessionKey200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sessionKey200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SessionKey200Response sessionKey200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sessionKey200Response.SessionKey == null)
                throw new ArgumentNullException(nameof(sessionKey200Response.SessionKey), "Property is required for class SessionKey200Response.");

            writer.WriteString("session_key", sessionKey200Response.SessionKey);
        }
    }

    /// <summary>
    /// The SessionKey200ResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(SessionKey200Response))]
    public partial class SessionKey200ResponseSerializationContext : JsonSerializerContext { }
}
